apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: gitea
spec:
  title: Gitea-Up
  icon: "https://docs.gitea.com/img/gitea.svg"
  statusInformers:
     - deployment/gitea
  ports:
    - serviceName: "gitea"
      servicePort: 3000
      localPort: 32000
      applicationUrl: "http://gitea"